import { IProduct } from './ProductsCard';

export const rawData: IProduct[] = [
  {
    name: 'Moonstone Crescent 18k Gold Plated Necklace',
    'product-code': 'RJ108',
    img: 'https://i.ibb.co/d0RG9jGz/67667e7a23de5.jpg',
    realPrice: '890',
    discountedPrice: '550',
    offer: '38',
    stock: '18',
    'description-top':
      'This enchanting necklace features a crescent moon-shaped pendant adorned with sparkling cubic zirconia stones and a central black moonstone that exudes mystery and elegance. The pendant is suspended from a twisted 18k gold-plated chain, adding a luxurious touch to this celestial-inspired design.\n\nMaterial: Premium alloy with 18k gold plating\nMain Stone: Black moonstone\nAccent Stones: Clear cubic zirconia\nColor: Gold with black and clear accents\nDesign: Crescent moon motif with a central moonstone\nWeight: Approximately 10 grams\nChain Length: 18 inches + 2-inch extender\nStyle: Mystical and elegant, perfect for both casual and formal wear\nThis necklace is an ideal choice for those who love celestial-inspired jewelry and want to add a touch of sophistication to their collection.',
    'description-bottom': 'Main Stone: Black moonstone\nAccent Stones: Clear cubic zirconia',
    material: 'Premium alloy with 18k gold plating',
    design: 'Crescent moon motif with a central moonstone',
    color: 'Gold with black and clear accents',
    category: '',
    weight: 'Approximately 10 grams',
    'chain length': '18 inches + 2-inch extender',
    style: 'Mystical and elegant, perfect for both casual and formal wear',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67e43de3cbc3281621448551',
  },
  {
    name: 'White Zircon Stylish Earrings',
    'product-code': 'RJ109',
    img: 'https://i.ibb.co/pjfGdj4n/O1-CN0100f8-WJ1xwi-Z3-Iin-Ku-2217845596508-0-cib.jpg',
    realPrice: '840',
    discountedPrice: '420',
    offer: '50',
    stock: '5',
    'description-top': 'White Zircon Stylish Earrings - RJ109',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f4e8b35d3389bb5fcc492a',
  },
  {
    name: 'Both Side Zircon Flower Earrings',
    'product-code': 'RJ101',
    img: 'https://i.ibb.co/7xWLBmnk/66816aa70875c-1.jpg',
    realPrice: '990',
    discountedPrice: '550',
    offer: '44',
    stock: '15',
    'description-top': 'Both Side Zircon Flower Earrings',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f4e98a4ff8d2e993a4a4f7',
  },
  {
    name: 'Sunflower Zircon Earrings',
    'product-code': 'RJ102',
    img: 'https://i.ibb.co/wZd8jSSt/O1-CN01-Figijc1kc-U6-L7-Idd8-2214373014704-0-cib.jpg',
    realPrice: '900',
    discountedPrice: '450',
    offer: '50',
    stock: '16',
    'description-top': 'Sunflower Zircon Earrings - RJ102',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f77c3db6e8c1abb623e01f',
  },
  {
    name: 'Starburst Cluster Hoop Earrings',
    'product-code': 'RJ103',
    img: 'https://i.ibb.co/Y4XZFwdL/O1-CN01u-Gl01-R26-YHk-Skl-S8-A-2208033727673-0-cib.jpg',
    realPrice: '990',
    discountedPrice: '490',
    offer: '50',
    stock: '20',
    'description-top':
      'These celestial-inspired earrings feature shimmering zircon stars delicately set on small gold hoops. Perfect for adding a touch of sparkle to any outfit.',
    'description-bottom':
      'Material: Gold-plated alloy, zircon stones.\nStyle: Celestial mini hoops.',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f7842f42dcd1b4bb912d98',
  },
  {
    name: 'Zircon Curve Ear Climber',
    'product-code': 'RJ104',
    img: 'https://i.ibb.co/zVCnFXzy/O1-CN01ey-WNt11w-TZo-WAr-Do-E-2217540066309-0-cib.jpg',
    realPrice: '990',
    discountedPrice: '490',
    offer: '54',
    stock: '60',
    'description-top':
      'Modern and sleek, these ear climbers feature a cascading design of high-quality zircon stones. They gracefully follow the ear curve for a contemporary look.',
    'description-bottom': '',
    material: 'Sterling silver-plated alloy, zircon stones.',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: 'Minimalist ear climber earrings.',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f785f4532ceade085f5ffb',
  },
  {
    name: 'Golden Mesh Circle Earrings',
    'product-code': 'RJ105',
    img: 'https://i.ibb.co/qYp2PY0F/6681737fc99a1.jpg',
    realPrice: '980',
    discountedPrice: '460',
    offer: '53',
    stock: '12',
    'description-top': 'Golden Mesh Circle Earrings - RJ105',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f788b43caef7191e5d4980',
  },
  {
    name: 'Golden Zircon Victorian Earrings',
    'product-code': 'RJ106',
    img: 'https://i.ibb.co/G3rvp096/O1-CN01pbq-JOD1mdy-Z98-Lnts-2211075024978-0-cib.jpg',
    realPrice: '990',
    discountedPrice: '550',
    offer: '44',
    stock: '10',
    'description-top': 'Golden Crystal Zircon Victorian Earrings',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f78a1ce004826d32cc6043',
  },
  {
    name: 'Double Layer Black Hollow Earrings',
    'product-code': 'RJ107',
    img: 'https://i.ibb.co/zHt0yZyK/O1-CN0169o-VCD1r-Ql-Cj-Esrbg-2215518975626-0-cib.jpg',
    realPrice: '699',
    discountedPrice: '450',
    offer: '36',
    stock: '15',
    'description-top': 'Double Layer Black Hollow Earrings - RJ107',
    'description-bottom': '',
    material: '',
    design: '',
    color: '',
    category: '',
    weight: '',
    'chain length': '',
    style: '',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f78bab3caef7191e5d4990',
  },
  {
    name: 'Pearl Shell Pendant 18k Gold Plated Necklace',
    'product-code': 'RJ110',
    img: 'https://i.ibb.co/KzpvwQHN/67667e8875450-1.jpg',
    realPrice: '890',
    discountedPrice: '590',
    offer: '34',
    stock: '0',
    'description-top':
      'This elegant necklace features a unique shell-shaped pendant that opens to reveal a lustrous faux pearl inside. The exterior of the shell is adorned with sparkling cubic zirconia stones, adding brilliance and luxury to the design. The pendant hangs gracefully from a twisted 18k gold-plated chain, making it a timeless and versatile piece.',
    'description-bottom':
      'This necklace is perfect for those who love sophisticated, ocean-inspired designs. It makes a thoughtful gift or a standout addition to any jewelry collection.',
    material: 'Premium alloy with 18k gold plating',
    design: 'Openable shell motif with hidden pearl detail',
    color: 'Gold with white pearl and clear accents',
    category: '',
    weight: 'Approximately 7 grams',
    'chain length': '18 inches + 2-inch extender',
    style: 'Luxurious and unique, ideal for both formal occasions and daily wear',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f78d86e004826d32cc605e',
  },
  {
    name: 'Pearl Heart Pendant 18k Gold Plated Necklace',
    'product-code': 'RJ111',
    img: 'https://i.ibb.co/jPP07FTH/67667f54159dc.jpg',
    realPrice: '990',
    discountedPrice: '650',
    offer: '34',
    stock: '0',
    'description-top':
      'This elegant necklace features a heart-shaped pendant with a luminous pearl center encased in a polished gold frame. The pendant is suspended from a sleek 18k gold-plated snake chain, creating a refined and timeless look. The combination of the smooth pearl and gold-plated finish makes this piece a symbol of love and sophistication.',
    'description-bottom':
      'This necklace is a perfect gift for expressing love or adding a romantic touch to your collection. Its versatile design ensures it complements any outfit beautifully.',
    material: 'Premium alloy with 18k gold plating',
    design: 'Heart-shaped pearl pendant on a gold snake chain',
    color: 'Gold with a white pearl accent',
    category: '',
    weight: 'Approximately 10 grams',
    'chain length': '16 inches + 2-inch extender',
    style: 'Classic and romantic, ideal for formal events or everyday elegance',
    isDeleted: false,
    isArrival: true,
    greenBox: '',
    status: '',
    id: '67f78e0ce004826d32cc6064',
  },
];
